### ISSUE TITLE
Some people are adding NSFW images

### ISSUE THREAD

**Issue by FrozenHearth** [Rama4/yelpcamp#1]
Just saw your Yelp Camp project on Heroku and I saw that some people are adding NSFW images to your project. You might want to look into that.

**Comment by AlexMachin1997** [comment]
I wouldnt say there NSFW images. However, if you @FrozenHearth wanted to block this he could add cloudinary api addons which can prevent adult content.

**Comment by FrozenHearth** [comment]
Well, one of them is a picture of an adult star, which seems pretty intentional by the guy who posted it.

Yeah he needs to do that, and first of all, delete those images.

**Comment by Rama4** [comment]
thanks for bringing up this issue to me

**Comment by AlexMachin1997** [comment]
As i previously mentioned you can add an adult content filter if you are using cloudinary. If adult content detected then it wont allow submission.

https://cloudinary.com/blog/automatic_image_moderation_removing_adult_or_inappropriate_photos_using_webpurify_and_cloudinary

**Comment by Rama4** [comment]
hey, can you check now?
i think i resolved it..

**Comment by AlexMachin1997** [comment]
Hey @Rama4 i got an internal server error when trying to upload a camp with an adult themed photo.

You might want to check your application log on heroku

**Comment by Rama4** [comment]
oops, i missed an open brace in a file.. fixed it
try now.. it should work..

**Comment by AlexMachin1997** [comment]
It shows awaiting moderation, is this what should happen ? i would take advantage of cloudinary API and automatically filter adult content out, it uses machine learning so its pretty accurate lol

**Comment by Rama4** [comment]
yeah it does use cloudinary api to automatically filter.. while awaiting response from cloudinary api, the text displayed for the user will be: awaiting moderation.
once the result has been received, if the image is accepted by the api, then the image is displayed automatically.. else "image rejected" text will appar to the user.

note: the texts "awaiting moderation" and "image rejected" are only visible to the owners of the image, when they are logged in. If you don't login, or login with as a different user, then no text is displayed for both the cases

**Comment by Rama4** [comment]
hey, i saw the logs, and it seems that webpurify was unable to load your image..
log:
{ error: 
       {    message: 'Resource not found - Error in loading https://www.pornhub.com/gif/16166312 - HTML response',
             status: 404
       }
}
